all:
	g++ -Wall -pthread *.cpp -o run `pkg-config --cflags --libs opencv` -I/usr/local/include/ -lraspicam -lraspicam_cv -lpigpio -lrt

#CXX ?= g ++

#CXXFLAGS += -c -Wall $(shell pkg-config --cflags --libs opencv)
#LDFLAGS += 
