all:
	g++ *.cpp -o output `pkg-config --cflags --libs opencv` -I/usr/local/include/ -lraspicam -lraspicam_cv

#CXX ?= g ++

#CXXFLAGS += -c -Wall $(shell pkg-config --cflags --libs opencv)
#LDFLAGS += 
